config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/new'

  get 'notifications/edit'

  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions: 'users/sessions'
    }

  devise_for :admins, controllers: { 
      sessions: 'admins/sessions'
    }

  get 'tags/:tag', to: 'videos#index', as: :tag
  get 'categories/:category', to: 'videos#index', as: :category
  resources :admins
  resources :users
  resources :videos
  resources :notifications

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'pages/landing' => 'high_voltage/pages#show', id: 'home'
  

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	validates_presence_of :headline
	validates_presence_of :content
	validates_length_of :headline, maximum: 50
	validates_length_of :content, maximum: 140
	belongs_to :admin
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	skip_before_filter :verify_authenticity_token
	before_action :authenticate_admin!
	layout 'user'

  def new
  	@notification = Notification.new
  end

  def create
  	@notification = Notification.new(notification_params)
  	@notification.admin_id = current_admin.id
	@notifications = Notification.all

	if @notification.save
		@notification.save
		if @notification.live == true
			@notifications.each do |notification|
				if notification != @notification
					notification.live = false
					notification.save
				end
			end
		end
		redirect_to notifications_path
	else
		render 'new'
	end
  end

  def edit
  	@notification = Notification.find(params[:id])
  end

  def update
  	@notification = Notification.find(params[:id])
	@notifications = Notification.all

	if @notification.update(notification_params)
		if @notification.live == true
			@notifications.each do |notification|
				if notification != @notification
					notification.live = false
					notification.save
				end
			end
		end

		redirect_to notifications_path
	else
		render 'edit'
	end
  end

  def index
  	@notifications = Notification.order('created_at DESC').paginate(:page => params[:page], :per_page => 6)
  end

  def destroy
  		@notification = Notification.find(params[:id])
		@notification.destroy

		flash[:notice] = "Successfully deleted notification."
		redirect_to notifications_path
  end

  private
  	def notification_params
  		params.require(:notification).permit(:headline, :content, :live)
	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= bootstrap_form_for @notification do |f| %>
  
  <% if @notification.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@notification.errors.count, "error") %> prohibited
    this notification from being created:</h2>
  
    <ul>
    <% @notification.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="panel">
    <div class="panel-body">
      <p>
        <%= f.text_field :headline %>
      </p>

      <p>
        <%= f.text_area :content, :size => "50x6", help: "(140 character max)" %>
      </p>

      <p>
        <%= f.check_box :live, label: "Publish?", value: true %>
      </p>

    </div>
  </div>

  <p>
    <%= f.submit "Create", class: "btn btn-default btn-block" %>
  </p>
<% end %>  

app/views/notifications/_update_form.html.erb
<%= bootstrap_form_for @notification do |f| %>
  
  <% if @notification.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@notification.errors.count, "error") %> prohibited
    this notification from being created:</h2>
  
    <ul>
    <% @notification.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.text_field :headline %>
  </p>
 
  <p>
    <%= f.text_area :content, :size => "50x6", help: "(140 character max)"%>
  </p>

  <p>
    <%= f.check_box :live, label: "Publish?" %>
  </p>

  <p>
    <%= f.submit "Update", class: "btn btn-default btn-block"%>
  </p>
<% end %>  

app/views/notifications/edit.html.erb
<html>
  <head>
  	<title><%= @notification.headline %></title>
  </head>
  <body>
      <div class="container">
      <br>
        <div class="row">
	  
        <!-- Edit Form -->
	    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
          <div class="panel panel-default">
	          <div class="panel-heading"><h4><i class="fa fa-edit fa-1x"> Edit Notification</h4></i></div>
	          <div class="panel-body"> 
		      	<%= render 'update_form' %>
		      </div>
	      </div>
    	</div>
	    
	    <!-- Sidebar -->
	      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 well well-lg">
				<%= link_to "Delete", notification_path, data: { confirm: "Are you sure?" }, method: :delete, :class => "btn btn-danger btn-block" %></p>
				<a class="btn btn-warning btn-block" role="button" href="<%= notifications_path %>" onclick="alert("Are you sure?");">Cancel</a>
	      </div>
        </div>
      </div>
  </body>
</html>

app/views/notifications/index.html.erb
<div class="container">
<br>
	<div class="well well-lg" style="background-color: #FFFFFF;">
		<h1 class="text-center"><i class="fa fa-bolt fa-2x"></i> Manage Notifications</h1><br>
	</div>
		<a class="btn btn-default" href="/notifications/new"><i class="fa fa-plus"></i> Create Notification</a>
		<div class="panel default">
			<div class="panel-body">
				<div class="container">
					<% @notifications.each do |notification| %>
								<div class="row">
									<h1><a href="<%= edit_notification_path(notification) %>"><%= notification.headline %></a></h1>
										<div class="btn-group">
											<% if admin_signed_in? %>
												<a type="button" href="<%= edit_notification_path(notification) %>" class="btn btn-default"><i class="fa fa-edit"></i> Edit</a> 
												<%= link_to notification_path(notification), method: :delete, data: { confirm: 'Are you sure?' } do %>
													<button class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
												<% end %>
											<% end %>
										</div>
								</div>
					<% end %>
				</div>
				<center><%= will_paginate @notifications, renderer: BootstrapPagination::Rails %></center>
			</div>
		</div>
</div>

app/views/notifications/new.html.erb
<html>    
    <div class="container">
    <br>
        <div class="row"> 
          <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
            <div class="panel panel-danger" style="border-color: #A50321;">
              <div class="panel-heading text-center" style="background-color: #A50321;"><h3><i class="fa fa-bolt"></i> Create Notification</h3></div>
              <div class="panel-body">
              <%= render 'form' %>
              </div>
            </div>
          </div>
          <div class="hidden-xs hidden-sm col-md-3 col-lg-3 well well-lg">
            <%= link_to "Cancel", current_admin, :class => "btn btn-default btn-block" %>
          </div>
          <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          
          </div>
        </div> 
    </div>
</html>