config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/new'

  get 'notifications/edit'

  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions: 'users/sessions'
    }

  devise_for :admins, controllers: { 
      sessions: 'admins/sessions'
    }

  get 'tags/:tag', to: 'videos#index', as: :tag
  get 'categories/:category', to: 'videos#index', as: :category
  resources :admins
  resources :users
  resources :videos
  resources :notifications

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'pages/landing' => 'high_voltage/pages#show', id: 'home'
  

end

app/models/video.rb
class Video < ActiveRecord::Base
	include AutoHtml

	validates_presence_of :title
	validates_presence_of :description
	validates_presence_of :url
	belongs_to :admin
	acts_as_taggable
	acts_as_taggable_on :categories

	auto_html_for :url do
		html_escape
		image
		youtube(:width => "100%", :height => "75%")
		link :target => "_blank", :rel => "nofollow"
		simple_format
	end

	def self.search(search)
	  if search
	    where('title ILIKE :search OR description ILIKE :search', search: "%#{search}%")
	    #where('description ILIKE ?', "%#{search}%")
	    #where('title ILIKE ?', "%#{search}%")
	  end
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :authenticate_admin!, :except => [:index, :show]
	layout 'user'

	include AutoHtml

	def new
		@video = Video.new
	end
	
	def create
		@video = Video.new(video_params)
		@video.admin_id = current_admin.id
		@video_client = YouTubeIt::Client.new(:dev_key => ENV["youtube_dev_key"])
		@video.thumbnail = @video_client.video_by(@video.url).thumbnails.first.url
		@videos = Video.all
		if @video.save
			@video.save
			if @video.featured == true
				@videos.each do |video|
					if video != @video
						video.featured = false
						video.save
					end
				end
			end
			redirect_to @video
		else
			render 'new'
		end
	end
	
	def show
		@video = Video.find(params[:id])
		@client = YouTubeIt::Client.new(:dev_key => ENV["youtube_dev_key"])
		@video2 = @client.video_by(@video.url)
	end
	
	def index
		if params[:tag]
			@videos = Video.tagged_with(params[:tag])

		elsif params[:category]
			@videos = Video.tagged_with(params[:category])
		
		elsif params[:search]
	  		@videos = Video.search(params[:search]).order('created_at DESC').paginate(:page => params[:page], :per_page => 6)
  		else
  			@videos = Video.order('created_at DESC').paginate(:page => params[:page], :per_page => 6)
  		end
  		@client = YouTubeIt::Client.new(:dev_key => ENV["youtube_dev_key"])
  		@video_array = []
  		@videos.each do |video|
  			@video_array.push([video,@client.video_by(video.url)])
  		end
  		@admins = Admin.paginate(:page => params[:page], :per_page => 2)
  		@admins = @admins.reverse_order
	end
	
	def edit
		@video = Video.find(params[:id])
	end
	
	def update
		@video = Video.find(params[:id])
		@videos = Video.all

		if @video.update(video_params)
			if @video.featured == true
				@videos.each do |video|
					if video != @video
						video.featured = false
						video.save
					end
				end
			end

			redirect_to @video
		else
			render 'edit'
		end
	end
	
	def destroy
		if current_admin.id == Video.find(params[:id]).admin_id
			@video = Video.find(params[:id])
			@video.destroy

			redirect_to videos_path
		else
			flash[:alert] = "Whoops! You can only delete videos you created."
			redirect_to current_admin
		end
	end
		      
	private
		def video_params
			params.require(:video).permit(:title, :description, :url, :code, :featured, :tag_list, :category_list)
		end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= bootstrap_form_for @video do |f| %>
  
  <% if @video.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@video.errors.count, "error") %> prohibited
    this video from being created:</h2>
  
    <ul>
    <% @video.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="panel">
    <div class="panel-body">
      <p>
        <%= f.text_field :title %>
      </p>

      <p>
        <%= f.text_area :description, :size => "50x6"%>
      </p>

      <p>
        <%= f.text_field :url, label: "YouTube URL" %>
      </p>

      <p>
        <%= f.text_area :code, label: "Code", help: "(paste code examples)", placeholder: "Enter Code Examples", :size => "50x6" %>
      </p>

      <p>
        <%= f.check_box :featured, label: "Feature Video", value: false %>
      </p>

      <p>
        <%= f.text_field :category_list, label: "Categories", help: "(seperate by commas)", placeholder: "Add Categories" %>
      </p>

      <p>
        <%= f.text_field :tag_list, label: "Tags", help: "(seperate by commas)", placeholder: "Add Tags" %>
      </p>

    </div>
  </div>

  <p>
    <%= f.submit "Create", class: "btn btn-default btn-block" %>
  </p>
<% end %>  

app/views/videos/_update_form.html.erb
<%= bootstrap_form_for @video do |f| %>
  
  <% if @video.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@video.errors.count, "error") %> prohibited
    this video from being created:</h2>
  
    <ul>
    <% @video.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.text_area :description, :size => "50x6" %>
  </p>

  <p>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.text_area :code, label: "Code", help: "(paste code examples)", placeholder: "Enter Code Examples", :size => "50x6" %>
  </p>

  <p>
    <%= f.check_box :featured, label: "Feature Video", value: false %>
  </p>

  <p>
    <%= f.text_field :category_list, label: "Categories", help: "(seperate by commas)", placeholder: "Add Categories" %>
  </p>

  <p>
    <%= f.text_field :tag_list, label: "Tags", help: "(seperate by commas)", placeholder: "Add Tags" %>
  </p>

  <p>
    <%= f.submit "Update", class: "btn btn-default btn-block"%>
  </p>
<% end %>  

app/views/videos/edit.html.erb
<html>
  <head>
  	<title><%= @video.title %></title>
  </head>
  <body>
      <div class="container">
      <br>
        <div class="row">
	  
        <!-- Edit Form -->
	    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
          <div class="panel panel-default">
	          <div class="panel-heading"><h4><i class="fa fa-edit fa-1x"> Edit Video</h4></i></div>
	          <div class="panel-body"> 
		      	<%= render 'update_form' %>
		      </div>
	      </div>
    	</div>
	    
	    <!-- Sidebar -->
	      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 well well-lg">
		    <!--<% if @video.thumbnail %>
			    <div class="panel panel-default">
				    <div class="panel-heading"><h5><i class="fa fa-image fa-1x"> Featured Image</i></h5></div>
				    <div class="panel-body text-center">
				    	<%= image_tag @video.thumbnail, size: "100%" %>
				    </div>
			    </div>
			<% end %>-->
				<%= link_to "Delete", video_path, data: { confirm: "Are you sure?" }, method: :delete, :class => "btn btn-danger btn-block" %></p>
				<a class="btn btn-warning btn-block" role="button" href="<%= video_path %>" onclick="alert("Are you sure?");">Cancel</a>
	      </div>
        </div>
      </div>
  </body>
</html>

app/views/videos/index.html.erb
<html>
	<head>
		  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag :defaults %>
		  <%= csrf_meta_tags %>
		  <link href="/assets/stylesheets/css/yeti2-bootstrap.css" rel="stylesheet">
		  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
		<title>Virt-U</title>
	</head>
	<body>
		<div class="container">
		<br>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="container well well-lg" style="background-color: #FFFFFF;padding: 30px;">
						<div class="col-lg-4">
							<%= form_tag(videos_path, :method => 'get', id: 'search-form', style: "padding-top: 10px;")  do %>
								<div class="input-group">
							    	<%= text_field_tag :search, params[:search], placeholder: "Search Videos...", class: "form-control input-lg", style: "display: inline;" %>
							    	<span class="input-group-btn">
							    		<%= submit_tag "Search", class: "form-button btn btn-danger btn-lg" %>
						    		</span>
						    	</div>
							<% end %>
						</div>
						<div class="col-lg-4">
							<div id="category_cloud" class="text-center">
								<h4>Popular Categories:</h4>
								<% tag_cloud Video.category_counts, %w[s m l] do |category, css_class| %>
									<%= link_to category.name, category_path(category.name), class: css_class, style: "color: #383838;" %>
								<% end %>
							</div>
						</div>
						<div class="col-lg-4">
							<div id="tag_cloud" class="text-center">
								<h4>Popular Tags:</h4>
								<% tag_cloud Video.tag_counts, %w[s m l] do |tag, css_class| %>
									<%= link_to tag.name, tag_path(tag.name), class: css_class, style: "color: #383838;" %>
								<% end %>
							</div>
						</div>
					</div>
					<% if admin_signed_in? %>
						<%= link_to new_video_path, id: "new_video" do %>
							<button class="btn btn-default"><i class="fa fa-plus"> </i> Add New Video</button>
						<% end %>
						<br>
					<% end %>
				</div>
			</div>
			<div class="row">
				<% @video_array.each do |video| %>
					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
						<div class="panel panel-default">
							<div class="panel-body">
								<div style="padding-bottom: 2px;">
									<%= raw video[0].url_html.gsub(/height="75%"*/, 'height="50%"') %>
								</div>
								<br>
								<%= link_to video_path(video[0]) do %>
									<h5 style="display: inline;">
										<%= video[0].title %>
									</h5>
								<% end %>
								<p>
									<%= truncate(video[0].description, length: 30, omission: '...(continued)') %>
								</p>
								<p>
									Categories: <%= raw video[0].category_list.map { |t| link_to t, category_path(t) }.join(', ') %>
								</p>
								<p style="display: inline;">
									Tags: <%= raw video[0].tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
								</p>
								<% if admin_signed_in? %>
								  <div class="btn-group pull-right">
				                    <a type="button" class="btn btn-default btn-sm" href="<%= edit_video_path(video[0]) %>">Edit</a> <%= link_to 'Delete', video_path(video[0]), :class => "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
				                  </div>
				                  <br>
			                  	<% end %>
							</div>
						</div>
					</div>
				<% end %>
			</div>
			<% if !params[:tag] && !params[:category] %>
				<%= will_paginate @videos, renderer: BootstrapPagination::Rails %>
			<% end %>	
		</div>
	</body>
</html>

app/views/videos/new.html.erb
<html>    
    <div class="container">
    <br>
        <div class="row"> 
          <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
            <div class="panel panel-danger" style="border-color: #A50321;">
              <div class="panel-heading text-center" style="background-color: #A50321;"><h3><i class="fa fa-youtube-play"></i> Add Video</h3></div>
              <div class="panel-body">
              <%= render 'form' %>
              </div>
            </div>
          </div>
          <div class="hidden-xs hidden-sm col-md-3 col-lg-3 well well-lg">
            <%= link_to "Cancel", videos_path, :class => "btn btn-default btn-block" %>
          </div>
          <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          
          </div>
        </div> 
    </div>
</html>

app/views/videos/new.js.erb
//$('#new_video').hide().after('<%= j render("form") %>')

app/views/videos/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= @video.title %></title>

    <!-- Bootstrap -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
    <br>
      <div class="col-lg-12 well well-lg" style="background-color: #FFFFFF;">
        <div class="row">
            <div class="text-center text-capitalize">
              <h1>
                <%= @video.title %> 
              </h1>
                <% if admin_signed_in? %>
                  <div class="btn-group">
                    <a type="button" class="btn btn-default btn-sm" href="<%= edit_video_path %>">Edit</a> <%= link_to 'Delete', video_path(@video), :class => "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                <% end %>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <br>
                <!--<%= raw @video2.embed_html5({class: 'video-player', id: 'my-video', width: '100%', height: '75%', frameborder: '0'}) %>-->
                <%= @video.url_html %>
                <!--<p><div class="video youtube"><iframe width="100%" height="50%" src="//www.youtube.com/embed/<%= @url %>" frameborder="0" allowfullscreen></iframe></div></p>-->
            </div>
        </div>
        <div class="row">
          <div class="col-lg-10 col-lg-offset-1">
            <br>
          	<p class="lead">
          	  <%= @video.description %>
          	</p>
            <kbd>
              <%= @video.code %>
            </kbd>
            <p>
              Categories: <%= raw @video.category_list.map { |t| link_to t, category_path(t) }.join(', ') %>
            </p>
            <p>
              Tags: <%= raw @video.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
            </p>
          </div>
        </div>
      </div>
      <%- disqus_thread %>
    </div>
  </body>
</html>