config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/new'

  get 'notifications/edit'

  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions: 'users/sessions'
    }

  devise_for :admins, controllers: { 
      sessions: 'admins/sessions'
    }

  get 'tags/:tag', to: 'videos#index', as: :tag
  get 'categories/:category', to: 'videos#index', as: :category
  resources :admins
  resources :users
  resources :videos
  resources :notifications

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'pages/landing' => 'high_voltage/pages#show', id: 'home'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VirtU</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/readable/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <script src="https://www.google.com/jsapi"></script>
  <script src="https://www.youtube.com/iframe_api"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <title>Virt-U</title>
</head>
<body style="background-color: #FFFFFF">
<%= disqus_init %>
  <% if flash.alert || flash.notice %>   
    	<% if flash.alert %>
        	<div id="flash" width="100%" style="padding: 0px;">
            <h6 class="alert alert-danger alert-dismissible" role="alert" width="100%" style="margin: 0px;border-radius: 0px;">
                <%= flash.alert %>
            </h6>
        	</div>
    	<% end %>
      <% if flash.notice %>
      	<div id="notice" width="100%" style="padding: 0px">
                <h6 class="alert alert-success alert-dismissible" role="alert" width="100%" style="margin: 0px;border-radius: 0px;">
                    <%= flash.notice %>
                </h6>   
      	</div>
      <% end %>
  <% end %>
  <%= yield %>
  <div class="container-fluid" style="background-color: #383838;">
  <div class="col-lg-3">
    <% if !admin_signed_in? && !user_signed_in? %>
      <h6 class="pull-left" style="padding: 30px; display: inline;"><a href="/users/sign_in" style="color: #FFFFFF;">Users</a></h6>
      <h6 class="pull-left" style="padding: 30px;"><a href="/admins/sign_in" style="color: #FFFFFF;">Admins</a></h6>
    <% end %>
  </div>
  <div class="col-lg-6">
    <h6 class="text-center" style="padding: 30px; color: #FFFFFF;">2015 Virt-U. Developed by <a href="http://ciregbulem.github.io" style="color: #FFFFFF;">Chudi Iregbulem</a></h6>
  </div>
  </div>

    <!-- Smooth Scroll -->
    <script type="text/javascript">
      (function (jQuery) {
        jQuery.mark = {
          jump: function (options) {
            var defaults = {
              selector: 'a.smooth-scroll'
            };
            if (typeof options == 'string') defaults.selector = options;
            var options = jQuery.extend(defaults, options);
            return jQuery(options.selector).click(function (e) {
              var jumpobj = jQuery(this);
              var target = jumpobj.attr('href');
              var thespeed = 1000;
              var offset = jQuery(target).offset().top;
              jQuery('html,body').animate({
                scrollTop: offset
              }, thespeed, 'swing')
              e.preventDefault();
            })
          }
        }
      })(jQuery);


      jQuery(function(){  
        jQuery.mark.jump();
      });
    </script><!-- Smooth Scroll -->
</body>
</html>

app/views/layouts/user.html.erb
<html height="100%">
<head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/readable/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <title>Virt-U</title>
</head>
<body style="background-color: #F7F7F7;" height="100%">
	<%= disqus_init %>
	<nav class="navbar navbar-inverse" style="border-radius: 0px; background-color: #A50321; border: 0px; border-bottom-color: #FFFFFF; border-bottom: solid #FFFFFF; margin-bottom: 0px;">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/" style="color: #FFFFFF">
	      	<img src="http://i.imgur.com/l78ajSa.png" class="img img-responsive" width="9.1%" height="9.1%">
	      </a>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
	      <% if user_signed_in? %>
		      <ul class="nav navbar-nav navbar-right">
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle text-capitalized" data-toggle="dropdown" role="button" aria-expanded="false"  style="color: #FFFFFF">
		          <% if current_user.fb_image %>
		          <%= image_tag current_user.fb_image, class: "img img-responsive img-rounded", width: "32", height: "28", style: "display: inline;" %> <%= current_user.fname %> 
		          <% end %>
		          <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		          	<li><a href="<%= user_path(current_user) %>">My Dashboard</a></li>
		            <li><a href="/users/edit">Edit Profile</a></li>
		            <li><a href="/users/edit#settings">Settings</a></li>
		            <li class="divider"></li>
		            <li><a href="/videos">View Videos</a></li>
		            <li class="divider"></li>
		            <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-block" %></li>
		          </ul>
		        </li>
		      </ul>

		  <% elsif admin_signed_in? %>
		      <ul class="nav navbar-nav navbar-right">
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle text-capitalized" data-toggle="dropdown" role="button" aria-expanded="false"  style="color: #FFFFFF">
		          <% if current_admin.avatar_file_name %>
		          	<%= image_tag current_admin.avatar.url(:medium), class: "img img-responsive img-rounded", width: "32", height: "28", style: "display: inline;" %> <%= current_admin.fname %>
	          	  <% else %>
	          	  	<%= image_tag "http://hanssietrainorphotography.com/wp-content/uploads/2013/06/facebook-no-image1.gif", class: "img img-responsive img-rounded", width: "32", height: "28", style: "display: inline;" %> <%= current_admin.fname %>
		          <% end %>
		          <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a href="/admins/edit">Edit Profile</a></li>
		            <li class="divider"></li>
		            <li><a href="/videos/new">Add Videos</a></li>
		            <li><a href="/videos">View Videos</a></li>
		            <li class="divider"></li>
		            <li><a href="/notifications/new">Add Notifications</a></li>
		            <li><a href="/notifications">View Notifications</a></li>
		            <li class="divider"></li>
		            <li><%= button_to "Sign Out", destroy_admin_session_path, method: :delete, class: "btn btn-default btn-block" %></li>
		          </ul>
		        </li>
		      </ul>
	      <% end %>
	      <!--<form class="navbar-form navbar-right" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>-->
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="/" style="color: #FFFFFF;">Home</a></li>
	        <li><a href="/videos" style="color: #FFFFFF;">Videos</a></li>
	        <!--<li><a href="/" style="color: #FFFFFF;">About</a></li>-->
	      </ul>
	    </div>
	  </div>
	</nav>
	<% if flash.alert || flash.notice %>   
	  	<% if flash.alert %>
	      	<div id="flash" width="100%" style="padding: 0px;">
	          <h6 class="alert alert-danger alert-dismissible" role="alert" width="100%" style="margin: 0px;border-radius: 0px;">
	              <%= flash.alert %>
	          </h6>
	      	</div>
	  	<% end %>
	    <% if flash.notice %>
	    	<div id="notice" width="100%" style="padding: 0px">
	              <h6 class="alert alert-success alert-dismissible" role="alert" width="100%" style="margin: 0px;border-radius: 0px;">
	                  <%= flash.notice %>
	              </h6>   
	    	</div>
	    <% end %>
	<% end %>
	<%= yield %>
	<br>
	<div class="container-fluid" style="background-color: #A50321;">
	  <div class="col-lg-3">
	    <% if !admin_signed_in? && !user_signed_in? %>
	      <h6 class="pull-left" style="padding: 30px; display: inline;"><a href="/users/sign_in" style="color: #FFFFFF;">Users</a></h6>
	      <h6 class="pull-left" style="padding: 30px;"><a href="/admins/sign_in" style="color: #FFFFFF;">Admins</a></h6>
	    <% end %>
	  </div>	
	  <div class="col-lg-6">
	    <h6 class="text-center" style="padding: 30px; color: #FFFFFF;">2015 Virt-U. Developed by <a href="http://ciregbulem.github.io" style="color: #FFFFFF;">Chudi Iregbulem</a></h6>
	  </div>
	</div>
</body>
</html>